### ISSUE TITLE
idea for function

### ISSUE THREAD

**Issue by Padmanabh82** [PCCoE-Hacktoberfest-21/react-app#12]
same like scroll button but it can take user to up and down also

**Comment by Padmanabh82** [comment]
please assign this issue to me

**Comment by ShamikG17** [comment]
This feature does not seem very useful. Also when opening an issue make sure you mention the feature in the title. So instead of "idea for function" you could write "Feature for scroll to bottom". Just a suggestion for contributing to open source :)

**Comment by Padmanabh82** [comment]
> This feature does not seem very useful. Also when opening an issue make sure you mention the feature in the title. So instead of "idea for function" you could write "Feature for scroll to bottom". Just a suggestion for contributing to open source :)

ok sir after i made it you just see it and tell me

**Comment by palakg01** [comment]
Hey @Padmanabh82 
As @ShamikG17 has clearly stated the feature is not useful so do not waste time working on it. Any PRs created for issues that have not been approved will be marked ```invalid```

**Comment by Padmanabh82** [comment]
> Hey @Padmanabh82 
> As @ShamikG17 has clearly stated the feature is not useful so do not waste time working on it. Any PRs created for issues that have not been approved will be marked ```invalid```

Ok but any one have new idea ??

**Comment by Padmanabh82** [comment]
I can make navbar create new issue and assign it to me

**Comment by Padmanabh82** [comment]
> I can make navbar create new issue and assign it to me

If you agree

**Comment by Padmanabh82** [comment]
Because navbar issue is closed

**Comment by ShamikG17** [comment]
@Padmanabh82 I request you to not spam comments and argue with the maintainers, else you will be blocked from contributing to this repository. Please abide by the code of conduct.

**Comment by Padmanabh82** [comment]
Ok sorry

**Comment by Padmanabh82** [comment]
And I wasn't arguing I was asking
