### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by shubhd556** [PCCoE-Hacktoberfest-21/react-app#13]
Creating a Responsive Navbar.

**Comment by Padmanabh82** [comment]
plese assine this issue to me 
i will make it

**Comment by ShamikG17** [comment]
Hey, @shubhd556 this issue is already open. I request you to go through the open issues before creating a new one. If you have any other feature you wish to implement you can open another issue for that.

**Comment by shubhd556** [comment]
Hey, @ShamikG17  I want to create some pages/components to the navbar. As of now there is only a title. Can I contribute with the previous Navbar issue?

**Comment by ShamikG17** [comment]
Sure @shubhd556 but right now that issue has already been assigned to someone. So after they work on it and make a PR you can add your features to that navbar. Is this fine? And we can continue this discussion on the previous navbar issue #1

**Comment by shubhd556** [comment]
@ShamikG17  Sure, we can.
