### ISSUE TITLE
New refresh button

### ISSUE THREAD

**Issue by Padmanabh82** [PCCoE-Hacktoberfest-21/react-app#14]
Sir I have an idea that will refresh all fake users

**Comment by Padmanabh82** [comment]
I will help to improve performance when Website will became big

**Comment by Padmanabh82** [comment]
Assign this to me

**Comment by ShamikG17** [comment]
This feature does not seem useful since anyways the users are refreshed when the user reloads the browser

**Comment by Padmanabh82** [comment]
Ok sir
