### ISSUE TITLE
New filter option

### ISSUE THREAD

**Issue by Padmanabh82** [PCCoE-Hacktoberfest-21/react-app#15]
Sir I have an idea for filtering fake users

**Comment by vedant-c** [comment]
What parameters will be there to filter users?

**Comment by Padmanabh82** [comment]
As you say. Age, living place,etc

**Comment by Padmanabh82** [comment]
`{
  "results": [
    {
      "gender": "male",
      "name": {
        "title": "mr",
        "first": "brad",
        "last": "gibson"
      },
      "location": {
        "street": "9278 new road",
        "city": "kilcoole",
        "state": "waterford",
        "postcode": "93027",
        "coordinates": {
          "latitude": "20.9267",
          "longitude": "-7.9310"
        },
        "timezone": {
          "offset": "-3:30",
          "description": "Newfoundland"
        }
      },
      "email": "brad.gibson@example.com",
      "login": {
        "uuid": "155e77ee-ba6d-486f-95ce-0e0c0fb4b919",
        "username": "silverswan131",
        "password": "firewall",
        "salt": "TQA1Gz7x",
        "md5": "dc523cb313b63dfe5be2140b0c05b3bc",
        "sha1": "7a4aa07d1bedcc6bcf4b7f8856643492c191540d",
        "sha256": "74364e96174afa7d17ee52dd2c9c7a4651fe1254f471a78bda0190135dcd3480"
      },
      "dob": {
        "date": "1993-07-20T09:44:18.674Z",
        "age": 26
      },
      "registered": {
        "date": "2002-05-21T10:59:49.966Z",
        "age": 17
      },
      "phone": "011-962-7516",
      "cell": "081-454-0666",
      "id": {
        "name": "PPS",
        "value": "0390511T"
      },
      "picture": {
        "large": "https://randomuser.me/api/portraits/men/75.jpg",
        "medium": "https://randomuser.me/api/portraits/med/men/75.jpg",
        "thumbnail": "https://randomuser.me/api/portraits/thumb/men/75.jpg"
      },
      "nat": "IE"
    }
  ],
  "info": {
    "seed": "fea8be3e64777240",
    "results": 1,
    "page": 1,
    "version": "1.3"
  }
}`

This are result parameters

**Comment by Padmanabh82** [comment]
Please assign this issue to me

**Comment by ShamikG17** [comment]
For now, you can make a filter that filters users according to their gender and age (ascending and descending order). Can you do this @Padmanabh82?

**Comment by Padmanabh82** [comment]
Ya sir i can

**Comment by Padmanabh82** [comment]
Please assign this issue to me

**Comment by ShamikG17** [comment]
@Padmanabh82 You may start working on the issue and make a PR after reading the contributing guidelines.

**Comment by Padmanabh82** [comment]
@ShamikG17 sir please see my other issue

**Comment by Padmanabh82** [comment]
Are you all people from Pune?? I am from Mumbai

**Comment by ShamikG17** [comment]
@Padmanabh82 I request you to keep the conversation strictly regarding the topic of the issue

**Comment by Padmanabh82** [comment]
Ok sorry @ShamikG17

**Comment by Padmanabh82** [comment]
@ShamikG17 sir i have made a pr please accept it
