### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by vedant-c** [PCCoE-Hacktoberfest-21/react-app#2]
Create a separate component for a footer to be added. Make sure it is responsive and attractive.

**Comment by Atharvamaid** [comment]
Hey @vedant-c ,
Can you assign me this issue ?

**Comment by Padmanabh82** [comment]
hey i want to work for this issue

**Comment by Padmanabh82** [comment]
I have mostly completed it. In 2 and half hour I can give

**Comment by Padmanabh82** [comment]
Sir please accept my pr #6 I have made a responsive footer in it

**Comment by Padmanabh82** [comment]
And also assin issue to me

**Comment by Padmanabh82** [comment]
sir please review my pr

**Comment by ShamikG17** [comment]
Hello @Padmanabh82, this issue has already been assigned to someone so you can't work on it right now. You may open more issues for features you want to add and I can assign that issue to you.

**Comment by Padmanabh82** [comment]
> Hello @Padmanabh82, this issue has already been assigned to someone so you can't work on it right now. You may open more issues for features you want to add and I can assign that issue to you.
> 

Can you accept my pr ??

**Comment by Padmanabh82** [comment]
Please
