### ISSUE TITLE
Add additional information about the user in the cards

### ISSUE THREAD

**Issue by ShamikG17** [PCCoE-Hacktoberfest-21/react-app#3]
Add additional information about the user in the cards like email, age, etc. 
You can check out the official API documentation(https://randomuser.me/documentation)

**Comment by Atharvamaid** [comment]
Hey @ShamikG17 ,
I would like to work on this issue.

**Comment by ShamikG17** [comment]
Sure @Atharvamaid you can go ahead and start working on the issue 👍
