### ISSUE TITLE
On clicking card should redirect to new page showing their profiles

### ISSUE THREAD

**Issue by Sejal-16** [PCCoE-Hacktoberfest-21/react-app#5]
When a user clicks onto a particular card , it should redirect to a separate page say /<User_name> and all details like their bio , and their social media links (hypothetical) can be displayed.

**Comment by Padmanabh82** [comment]
If you give me design I will make it

**Comment by Padmanabh82** [comment]
Mean "layout"

**Comment by Padmanabh82** [comment]
Please assign this issue to me

**Comment by Padmanabh82** [comment]
@Sejal-16 please give me layout
