### ISSUE TITLE
idea for new function

### ISSUE THREAD

**Issue by Padmanabh82** [PCCoE-Hacktoberfest-21/react-app#7]
i have an idea for **back to top** button I will make it. but assign this issue to me

**Comment by ShamikG17** [comment]
Sure @Padmanabh82 you can start working on this

**Comment by Padmanabh82** [comment]
> Sure @Padmanabh82 you can start working on this 

Sir any other Idea?? I have done this. I will make a pr

**Comment by Padmanabh82** [comment]
Sir I have made a pr but tell why it is failing in test ??
